name: sized_context
description: Access MediaQuery sizing info directly on the context, also adds some helper methods for sizing and layout.
version: 1.0.0+4
homepage: https://github.com/gskinnerTeam/flutter-sized-context
issue_tracker: https://github.com/gskinnerTeam/flutter-sized-context/issues

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  universal_platform: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0